### ISSUE TITLE
Invisible fluids from Tinker's Constructs

### ISSUE THREAD

**Issue by Herbing1** [Alpha-s-Stuff/TinkersConstruct#10]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.8

### Fabric/Quilt API Version

0.58.0-1.18.2

### Tinkers' Construct Version

TConstruct-1.18.2-3.5.1.DEV.cc5281c

### Describe your issue

When I enable a shaderpack (like BSL or any other one), fluids of TC in the smeltery, and the tanks are rendered invisible. Pouring liquids into casts renders them invisible as well. Even the cooling down block is invisible.
![2022-08-06_16 06 05](https://user-images.githubusercontent.com/92773080/183240779-5788ffbb-d6aa-4218-bae4-dfa53c635548.png)
![2022-08-06_16 06 10](https://user-images.githubusercontent.com/92773080/183240788-47d58684-3761-495d-a6f5-3551b6780c4f.png)
![2022-08-06_16 05 56](https://user-images.githubusercontent.com/92773080/183240833-1d71d2e5-0328-4238-9e13-4d9dfd25d410.png)

### Other mods

sodium-fabric-mc1.18.2-0.4.1+build.15
indium-1.0.7+mc1.18.2
fabric-api-0.58.0+1.18.2
iris-mc1.18.2-1.2.6
shaderpack: ComplementaryReimagined_r1.1.1

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium

### Searched for known issues?

Checked the FAQ

**Comment by Herbing1** [comment]
and when I disable the shaderpack, everything seems normal again.

**Comment by AlphaMode** [comment]
Apparently Iris doesn't support custom vertex formats so I don't think this is fixable from tinkers side
