### ISSUE TITLE
Piercing damage does not work

### ISSUE THREAD

**Issue by magical911plane** [Alpha-s-Stuff/TinkersConstruct#101]
### Minecraft Version

1.20.1

### Fabric Version

0.15.3

### Fabric API Version

0.91.0-1.20.1

### Hephaestus Version

1.20.1-3.6.3.241

### Describe your issue

Piercing damage seems to act just like normal damage, not being able to bypass the armor.

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by AlphaMode** [comment]
I believe this was fixed in this commit https://github.com/Alpha-s-Stuff/TinkersConstruct/commit/cf48189c29e43f2e3d854126dfd5972bb1804abe
