### ISSUE TITLE
Items not dropping

### ISSUE THREAD

**Issue by TheUnChosenOne** [Alpha-s-Stuff/TinkersConstruct#104]
### Minecraft Version

1.20.1

### Fabric Version

1.15.6

### Fabric API Version

0.91.0

### Hephaestus Version

3.6.3.241

### Describe your issue

Item's not dropping when broken when craft tweaker added.

### Other mods

tweaker mod

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KonSola5** [comment]
Porting Lib issue, see https://github.com/Fabricators-of-Create/Porting-Lib/issues/74.

**Comment by AlphaMode** [comment]
Should already be fixed
