### ISSUE TITLE
sodium plus hephaestus causing text to corrupt and game crash when loading a world

### ISSUE THREAD

**Issue by likeaboss90002** [Alpha-s-Stuff/TinkersConstruct#105]
### Minecraft Version

1.20.1

### Fabric Version

0.15.6

### Fabric API Version

0.92.0+1.20.1

### Hephaestus Version

1.20.1-3.6.3.240

### Describe your issue

when loading up minecraft with sodium and heplaestus, minecraft's font doesnt load correctly and when entering a world like this crashes the game
![2024-02-25_18 14 07](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/47680827/4ccd500d-4720-44c7-b0b6-58c5adf6a74a)

### Crash Report

https://gist.github.com/likeaboss90002/5be8e23d2396e568d23c58eaf7297ffa

### Other mods

roughly enough items
roughly enough resources
noisium

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

Searched closed issues

**Comment by AlphaMode** [comment]
You need to install indium https://modrinth.com/mod/indium

**Comment by likeaboss90002** [comment]
oh thanks, i didnt expect a fast reply, and also i didnt realize to use that mod
