### ISSUE TITLE
Crash when trying to use the output of a drain as fuel to the same smelter

### ISSUE THREAD

**Issue by Pietagorh** [Alpha-s-Stuff/TinkersConstruct#108]
### Minecraft Version

1.20.1

### Fabric Version

0.15.6

### Fabric API Version

0.92.0+1.20.1

### Hephaestus Version

1.20.1-3.6.3.240

### Describe your issue

When using the liquid inside of a smelter as fuel for the same smelter, the game will crash
Here's a video demonstrating the issue: https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/60353007/ee8f236d-49a7-432d-87df-902514570f72 (I right clicked the faucet before the crash)

### Crash Report

https://pastebin.com/pmYpyngR

### Other mods

- Mod Menu
- Fabric API

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by AlphaMode** [comment]
Can you try on the newest version 3.6.4.270?

**Comment by Pietagorh** [comment]
For some reason I can't launch anything after 3.6.4.241
![image](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/60353007/57bff397-127c-404b-954e-48aa56a83c41)

**Comment by AlphaMode** [comment]
I've never seen that error before weird... Maybe try reinstalling fabric?

**Comment by AlphaMode** [comment]
You can also try updating fabric api

**Comment by Pietagorh** [comment]
Fabric API is up to date
I tried with Fabric 0.15.7 and the game launched

**Comment by Pietagorh** [comment]
And welp seems like this works with the latest version
Sorry for the unnecessary issue then x) and thanks for the fast replies!

**Comment by AlphaMode** [comment]
Its no problem, glad I was able to help!
