### ISSUE TITLE
Foliage loot tables dont work (leaves, ferns)

### ISSUE THREAD

**Issue by StockiesLad** [Alpha-s-Stuff/TinkersConstruct#11]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.9

### Fabric/Quilt API Version

0.58.0-1.18.2

### Tinkers' Construct Version

TConstruct-1.18.2-3.5.1.DEV.cc5281c

### Describe your issue

Cant get drops from leaves

### Other mods

https://www.technicpack.net/modpack/the-limit-reborn-1181.1905659

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

Checked pinned issues, Searched open issues, Checked the FAQ

**Comment by AlphaMode** [comment]
Can you go more in detail about this I can't seem to reproduce this

**Comment by StockiesLad** [comment]
They don't parse as it uses "forge:can_tool_perform_action".

**Comment by AlphaMode** [comment]
Can you please give proper reproductions steps I'm still not entirely sure what the issue is

**Comment by StockiesLad** [comment]
just try to break leaves with shears, or anything. there will be no drops

**Comment by StockiesLad** [comment]
It works on the latest update now...
