### ISSUE TITLE
Items stored in workbenches are lost when the station is mined

### ISSUE THREAD

**Issue by myriapoleis** [Alpha-s-Stuff/TinkersConstruct#123]
### Minecraft Version

1.20.1

### Fabric Version

0.15.10

### Fabric API Version

0.92.1

### Hephaestus Version

3.6.4.273

### Describe your issue

Items stay in workbenches when the interface is closed, however, are lost upon the work bench being mined. Picking up the dropped workbench item and placing it down also shows that nbt data isnt saved in the item, if that is the intended behavior(?).

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched closed issues

**Comment by DJChaos42** [comment]
Confirmed for version 3.6.4.274.

Blocks which were tested and affected : Crafting Station, Tinker Station, Part Builder, Tinker's Chest, Part Chest, Modifier Worktable, Tinker's Anvil, Smeltery Controller, Foundry Controller, Casting Basin, Casting Table, Seared Melter, Scorched Alloyer.

Blocks which were tested, but unaffected: Cast Chest, all tank variants.

**Comment by thelyric27** [comment]
I'm still experiencing this as of Hephaestus 3.6.4.287
