### ISSUE TITLE
Smelteries and fluid deletion

### ISSUE THREAD

**Issue by Mieridduryn** [Alpha-s-Stuff/TinkersConstruct#126]
### Minecraft Version

1.20.1

### Fabric Version

0.15.10

### Fabric API Version

0.92.1+1.20.1

### Hephaestus Version

1.20.1-3.6.4.271

### Describe your issue

When one right-clicks a smeltery drain with a bucket (or something that behaves as a bucket), *all* fluid of the type you have bucketed will disappear from the smeltery, no matter the capacity of the bucket you use.
For example, if I have 4000mb milk in my smeltery, and I right-click a vanilla bucket on the drain, all 4000mb of milk disappears from the smeltery, yet I only receive one bucket of milk in return.

### Other mods

All of Fabric 7 modpack.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium, Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by Mieridduryn** [comment]
I say smeltery, but I mean smelteries *and* foundries.

**Comment by Valanaro** [comment]
Also have the same issue in All of Fabric 7.
Very frustrating to accidentally delete materials when being slightly off right clicking the faucet.

If intended to be able to delete materials then I'd rather have a fourth drain type for waste or a verification check.

**Comment by Jurakii** [comment]
Just had this issue, i believe it also can happen when you right click with tools, possibly anything with right click functionality, it happened with my sword

**Comment by Nibroc-64** [comment]
I'm still getting this issue on version 1.20.1-364.287. I can open a seperate issue if needed, but evidently the fix has not made it's way into the 1.20.1 branch.
