### ISSUE TITLE
[Zenith conflict] Heph tools are always counted as light weapons by Zenith

### ISSUE THREAD

**Issue by Mieridduryn** [Alpha-s-Stuff/TinkersConstruct#127]
### Minecraft Version

1.20.1

### Fabric Version

0.15.10

### Fabric API Version

0.92.1+1.20.1

### Hephaestus Version

1.20.1-3.6.4.271

### Describe your issue

Zenith counts every single Heph tool as a "light weapon," resulting in mining tools such as sledgehammers being treated as if they were swords. I cannot put gems intended for mining tools on my sledgehammer, and rerolling its affixes gives it weapon affixes.

Hephaestus and Zenith are Fabric ports of Tinker's Construct and Apotheosis, respectively.
When tested on Forge, with Tinker's Construct and Apotheosis, this mechanic works as intended. Mining tools get mining tool affixes.

There's apparently an affix override thingie in the config that can be altered to fix this, or so I saw in a conversation about this kind of issue in the AOF server.

### Other mods

All Of Fabric 7, someone else (stellaroomy) tested this on Forge with the non-ported mods for me with ONLY TConstruct and Apotheosis.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium, Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by TheWinABagel** [comment]
Ngl this ones on me
I removed support for some porting lib modules and one of the ones was tool actions
I'll readd it whenever i can muster up the motivation to look at zenith...
Regardless this isn't a heph issue
