### ISSUE TITLE
Crashes with Sodium

### ISSUE THREAD

**Issue by Roboaussie** [Alpha-s-Stuff/TinkersConstruct#128]
### Minecraft Version

1.20.1

### Fabric Version

0.15.1

### Fabric API Version

0.92.1

### Hephaestus Version

3.6.4.273

### Describe your issue

Installing any version of Sodium crashes with this mod, any version of this mod with any version of sodium 0.51 and up causes a crash when booting into the game. Removing any type of sodium and its mod addons stops the crashing.

### Other mods

Sodium, Iris, Sodium Extra, Reese's sodium options

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues

**Comment by AlphaMode** [comment]
Do you have indium installed? You didn't post a crash log or modlist...

**Comment by Roboaussie** [comment]
No I dont have indium installed- Sorry those were the only mods in the other mods section I found necessary since trying with anything else didn't seem to affect it.

**Comment by AlphaMode** [comment]
You need https://modrinth.com/mod/indium in order to use sodium with hephaestus.

**Comment by Roboaussie** [comment]
Oh I did not know that, thank you!
