### ISSUE TITLE
Mod cannot work with create-0.5.0 on the server

### ISSUE THREAD

**Issue by Mikm159** [Alpha-s-Stuff/TinkersConstruct#13]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.8

### Fabric/Quilt API Version

0.57.0 1.18.2

### Tinkers' Construct Version

TConstruct-1.18.2-3.5.1.DEV.dacc01d

### Describe your issue

When TConstruct-1.18.2-3.5.1.DEV.dacc01d and create-1.18.2-0.5.0c-683 are loaded on the server at the same time, the player cannot join the server normally. These two mods perform normally in local games. Actually, TConstruct-1.18.2-3.5.1.DEV.cc5281c works normally on the server with create-1.18.2-0.5.0c-683.
Player interface
![image](https://user-images.githubusercontent.com/99482689/183530176-df14ba4f-c795-4c3e-9817-c6f7cd7c7006.png)
Server logs
[latest.log](https://github.com/Alpha-s-Stuff/TinkersConstruct/files/9285510/latest.log)

### Crash Report

No crash

### Other mods

create-1.18.2-0.5.0c-683
fabric-api-0.57.0+1.18.2

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues

**Comment by AlphaMode** [comment]
can you send a client log please

**Comment by Mikm159** [comment]
Sure, just a moment, please

**Comment by Mikm159** [comment]
[minecraft-exported-logs-2022-08-09T07-21-03.log](https://github.com/Alpha-s-Stuff/TinkersConstruct/files/9285526/minecraft-exported-logs-2022-08-09T07-21-03.log)

**Comment by AlphaMode** [comment]
Can you try on latest build?

**Comment by Mikm159** [comment]
Congratulations! Mod seems to work perfectly on the server!
