### ISSUE TITLE
[Compat] EMI

### ISSUE THREAD

**Issue by sleepingdragoninn** [Alpha-s-Stuff/TinkersConstruct#14]
### Minecraft Version

N/A

### Forge Version

N/A

### Mantle Version

N/A

### Tinkers' Construct Version

N/A

### Problem description

This is probably another one of those issues that's just gonna sit here until we do it ourselves - and that's okay. I just wanted to at least document a reminder for us ahahah.

This port has some REI integration through its API, but it doesn't have the same level of integration through [EMI](https://modrinth.com/mod/emi)'s API.

### Suggested solution

Someone (us, probably) reimplements the REI integration in EMI's API. 

### Alternatives considered

Someone who isn't us could reimplement the integration in EMI. That would probably be faster - Our current rate on being able to PR things is mostly "when we learn how to do the required development"-dependent, so it may be a couple months out before we start.

EMI is also going multiplat at some point (we think) so we could technically wait, and then be bothersome upstream insteead - but we think it would be more realistic to do it here and then try to port/PR there anyway.

### Additional context

Apologies for posting this right after the REI integration went in, We just didn't think of it until that prompted us lmao

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by AlphaMode** [comment]
I'm personally not going to implement EMI compatibility I dont like the idea of maintaining 3 recipe viewers and I also don't have time to ethier

**Comment by dhouck** [comment]
Fortunately this is being worked on by https://github.com/Kneelawk/extra-mod-integrations.
