### ISSUE TITLE
Axe Disfunction

### ISSUE THREAD

**Issue by EvantheGrump** [Alpha-s-Stuff/TinkersConstruct#143]
### Minecraft Version

1.20.1

### Fabric Version

Quilt 0.26.3

### Fabric API Version

7.6.0

### Hephaestus Version

1.20.1-3.6.4.279

### Describe your issue

None of the axes added by Hephaestus are compatible with any tree-chopping mod. Tested tree chopping mods include:
Panda's falling trees
Falling Tree
HT Tree Chop
Tree Harvester

Interestingly, HT Tree Chop shows an icon near the crosshair when the player is targeting a natural tree and holding an appropriate tree-chopping tool. Hephaestus hand axes show this icon and take an extended amount of time to cut the tree, as is a feature of the mod, but still only destroys one log.

### Other mods

I tested each tree chopping mod above with exclusively its libraries and Hephaestus.
I also tried using fabric instead of quilt.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by Rakambda** [comment]
Hello, I'm the author or FallingTree that was mentionned above. I had a report mentionning that compatibility too on Discord.

In the case of my mod, it hooks itself with `PlayerBlockBreakEvents.Before` (API provided by fabric), however in the case of the axes provided by Hephaestus this method is never triggered. Probably the block is simply removed from the world without attributing it to the player. (my guess would be it has something to do with what is performed by this method https://github.com/Alpha-s-Stuff/TinkersConstruct/blob/1.20.1/src/main/java/slimeknights/tconstruct/library/tools/helper/ToolHarvestLogic.java#L281)

This is probably linked, but breaking logs with axes also doesn't increase the number of logs bloken in the Statistic tab of the player.

**Comment by unilock** [comment]
Probably a duplicate of https://github.com/Alpha-s-Stuff/TinkersConstruct/issues/82.  
You can use this mod to work around the issue in the meantime: https://github.com/unilock/NotTamago

**Comment by EvantheGrump** [comment]
Thanks for your help!
