### ISSUE TITLE
Slime islands do not spawn

### ISSUE THREAD

**Issue by NyakoFox** [Alpha-s-Stuff/TinkersConstruct#15]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.9

### Fabric/Quilt API Version

0.58.0+1.18.2

### Tinkers' Construct Version

1.18.2-3.5.1.DEV.85b8f33

### Describe your issue

It looks like slime islands don't spawn naturally, making skyslime pretty hard to get. I couldn't find any skyslime geodes either (flying around in spectator) however there were a few earthslime geodes, so maybe it was just bad luck. I'm fully aware it could just be commented out or something since the port is unfinished, but I couldn't find any info about them (and they looked implemented from looking through the code) so I thought I'd ask about it.

### Other mods

The modpack is Cabricality. (It's public don't worry)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by AlphaMode** [comment]
They were working before but I think I accidentally disabled them I noticed this a few days ago when I created a new world

**Comment by AlphaMode** [comment]
Fixed in latest commit
