### ISSUE TITLE
logs rotate when stripped with Hand axe or Broad Axe

### ISSUE THREAD

**Issue by dutch-gamer** [Alpha-s-Stuff/TinkersConstruct#153]
### Minecraft Version

1.20.1

### Fabric Version

0.16.7

### Fabric API Version

0.92.21.20.1

### Hephaestus Version

Hephaestus-1.20.1-3.6.4.279

### Describe your issue

Action:
Right-clicking on a log, in either the x or z orientation, with any Broad Axe or Hand axe to strip the log

Result:
the log is rotated to the y axis and is stripped.

expected:
the log should be stripped and still be in the same orientation as the log before stripping

### Other mods

Just Hephaestus and its dependencies

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by AlphaMode** [comment]
Fixed in latest commit
