### ISSUE TITLE
Loot table modifications seem broken

### ISSUE THREAD

**Issue by NyakoFox** [Alpha-s-Stuff/TinkersConstruct#17]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.9

### Fabric/Quilt API Version

0.58.0+1.18.2

### Tinkers' Construct Version

1.18.2-3.5.1.DEV.f5a7942

### Describe your issue

The loot tables don't seem to be set up right. While I don't exactly know where it's going wrong, I know that wither skeletons don't drop necrotic bones despite the config option being true, and blazes don't drop blaze heads despite me and a friend both killing them for an hour with our cleavers. I know that the json files are datagenned correctly (or at least they're present) and something else must not be going right.

### Other mods

![image](https://user-images.githubusercontent.com/87289390/184517764-05be38bd-3dd2-402b-81a3-f112472de9f7.png)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by Reimnop** [comment]
Can confirm, happens to me too.
