### ISSUE TITLE
Crash when using Melter with Seared Tank

### ISSUE THREAD

**Issue by SylviBlossom** [Alpha-s-Stuff/TinkersConstruct#19]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.9

### Fabric/Quilt API Version

0.58.0+1.18.2

### Tinkers' Construct Version

1.18.2-3.5.1.DEV.33b3fef

### Describe your issue

Right-clicking on a Seared Melter with a Seared Tank placed underneath it (with or without fluid) crashes the game. The melter doesn't crash with a heater placed below it.

### Crash Report

https://gist.github.com/SylviBlossom/cb744f718489b5288866201d22706082

### Other mods

No other mods

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ZZZank** [comment]
The same thing happened to me.
