### ISSUE TITLE
mod compat tools for twilight forest don't exist

### ISSUE THREAD

**Issue by unix-supremacist** [Alpha-s-Stuff/TinkersConstruct#2]
### Minecraft Version

1.18.2

### Forge Version

the good forge 0.14.8

### Mantle Version

its jar in jared what the fuck

### Tinkers' Construct Version

1.18.2-3.5.1.DEV.dd9ddc9

### Describe your issue

twilight forest material compat doesn't work

### Other mods

this shouldn't matter but

[15:23:03] [main/INFO]: Loading 361 mods:
	- additionalentityattributes 1.0.0+1.18.2 via spectrum
	- advanced_runtime_resource_pack 0.5.7 via dynamic_asset_generator
	- ae2 11.1.3
	- ae2things 1.1.0-beta.7
	- alternate-current 1.4.0
	- apoli 2.3.3 via origins
	- arcanus 1.29
	- architectury 4.5.76
	- attributefix 14.0.2
	- audio_engine_tweaks 1.2.2
	- autoconfig1u 3.4.0
	- automatone 0.7.0 via requiem
	- autotag 1.1.0
	- badpackets 0.1.2
	- bannerpp 2.0.6-teb.1+mc.1.18.2 via spectrum
	- bebooks 1.3.1
	- besmirchment 1.18.2-11
	- betterbeds 1.2.0
	- betterfpsdist 1.18-1.8
	- bewitchment 1.18-23
	- beyond_earth 1.0.0
	- blabber 0.2.0 via requiem
	- blanket-client-tweaks 1.0.4
	- blue_endless_jankson 1.2.1 via ngroklan
	- botania 1.18.2-434-FABRIC
	- buildinggadgets 1.0.22
	- bwplus 1.18.2-17
	- byg 1.4
	- c2me 0.2.0+alpha.7.27
	- c2me-base 0.2.0+alpha.7.27 via c2me
	- c2me-client-uncapvd 0.2.0+alpha.7.27 via c2me
	- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.7.27 via c2me
	- c2me-fixes-general-threading-issues 0.2.0+alpha.7.27 via c2me
	- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.7.27 via c2me
	- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.7.27 via c2me
	- c2me-notickvd 0.2.0+alpha.7.27 via c2me
	- c2me-opts-allocs 0.2.0+alpha.7.27 via c2me
	- c2me-opts-chunk-access 0.2.0+alpha.7.27 via c2me
	- c2me-opts-chunkio 0.2.0+alpha.7.27 via c2me
	- c2me-opts-math 0.2.0+alpha.7.27 via c2me
	- c2me-opts-scheduling 0.2.0+alpha.7.27 via c2me
	- c2me-opts-worldgen-general 0.2.0+alpha.7.27 via c2me
	- c2me-opts-worldgen-vanilla 0.2.0+alpha.7.27 via c2me
	- c2me-rewrites-chunkio 0.2.0+alpha.7.27 via c2me
	- c2me-server-utils 0.2.0+alpha.7.27 via c2me
	- c2me-threading-chunkio 0.2.0+alpha.7.27 via c2me
	- c2me-threading-lighting 0.2.0+alpha.7.27 via c2me
	- c2me-threading-scheduling 0.2.0+alpha.7.27 via c2me
	- c2me-threading-worldgen 0.2.0+alpha.7.27 via c2me
	- caffeineconfig 1.1.0 via sodium-extra
	- calio 1.5.1 via apoli
	- can-i-mine-this-block 1.2.0
	- cardinal-components 4.2.0
	- cardinal-components-base 4.2.0 via cardinal-components
	- cardinal-components-block 4.2.0 via cardinal-components
	- cardinal-components-chunk 4.2.0 via cardinal-components
	- cardinal-components-entity 4.2.0 via cardinal-components
	- cardinal-components-item 4.2.0 via cardinal-components
	- cardinal-components-level 4.2.0 via cardinal-components
	- cardinal-components-scoreboard 4.2.0 via cardinal-components
	- cardinal-components-world 4.2.0 via cardinal-components
	- carpet 1.4.69
	- carpet-extra 1.4.72
	- carpet-tis-addition 1.37.0
	- chime 1.2.1 via requiem
	- chisel 1.4.5
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.2.62
	- cloth-config-lite 2.0.6 via omega-config-gui
	- cloth-utils-v1 2.0.54 via computercraft
	- clumps 8.0.0+10
	- com_electronwill_night-config_core 3.6.5 via c2me
	- com_electronwill_night-config_toml 3.6.5 via c2me
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_flowpowered_flow-math 1.0.3 via dimdoors
	- com_github_alexdlaird_java-ngrok 1.5.6 via ngroklan
	- com_github_dimensionaldevelopment_poly2tri_java 0.1.1 via dimdoors
	- com_github_llamalad7_mixinextras 0.0.10 via extended_drawers
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_ibm_async_asyncutil 0.1.0 via c2me
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- com_refinedmods_refinedstorage2_refinedstorage2-query-parser_ 2.0.0-milestone.1.4 via refinedstorage2
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- completeconfig 1.4.1 via progressivebosses
	- computercraft 1.100.8
	- conditional-mixin 0.3.0 via carpet-tis-addition
	- coxinhautilities 1.3+1.18.2
	- create mc1.18.2_v0.4.1+637
	- createaddition ${version}
	- createdeco 1.2.7a-fabric-1.18.2
	- createplus 1.0
	- crowdin-translate 1.4+1.18.2 via smoke_suppression
	- cullleaves 2.3.2
	- curse_maven_wthit-3707010 440979 via dimdoors
	- customportalapi 0.0.1-beta50-1.18 via the_aether
	- dark-enchanting 1.0.0+1.18.2
	- darkrites 1.18.2-1
	- dawn 3.3.0
	- de_poiu_apron_apron 2.1.1 via mconfig
	- dimdoors 4.0.4
	- dragonfight 1.18.2-2.5
	- dripstone_fluid_lib 1.2.0 via milk
	- dynamic-lights 1.0.3+1.18.2
	- dynamic_asset_generator 0.6.2
	- dynamicfps 2.1.0
	- elementalcreepers 1.4.2+1.18.2
	- elytratrinket 3.0.0-1.18.1
	- endermangrief 0.2
	- enhancedblockentities 0.7.1+1.18.2
	- entityculling 1.5.1
	- excavated_variants 0.6.4
	- extended_armor_bars 1.2.1
	- extended_drawers 1.2.2+mc.1.18.2
	- extragenerators 1.2.1-BETA+1.18
	- fabric 0.57.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.22+d7c144a860 via fabric
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-data-generation-api-v1 3.0.0+9fcb91d260 via fabric
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.18+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.1+6c4e5d0960 via fabric
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.8.1+kotlin.1.7.0
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.22+e6b169eb60 via fabric
	- fabric-networking-v0 0.3.9+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment
	- fabric-registry-sync-v0 0.9.9+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.2+d005b03a60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.2+446e059560 via hydrogen
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.1+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
	- fabricated-forge-caps 04a7b3af01 via tesseractapi
	- fabricloader 0.14.8
	- fake-player-api 0.3.0 via create
	- farmersdelight 1.18.2-0.2.1
	- fastload 1.1.5
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via requiem
	- fiber2cloth 3.1.1 via requiem
	- finitewater 4.0-1.18.2
	- flywheel 1.18-0.7.0.26 via create
	- forge_tags 2.1 via create
	- forgeconfigapiport 3.2.0
	- forgetmechunk 1.0.4-1.18.X-1.19.X
	- gateofbabylon 1.7.0-1.18.2
	- geckolib3 3.0.50
	- golemsgalore 1.2.1+1.18.2
	- graphlib 0.2.4+1.18.2 via extended_drawers
	- greater_eye 1.3.25
	- gud_creeper_swarm 1.0.0
	- gud_recipe_confidence 1.0.2 via the_aether
	- healthoverlay 6.2.4
	- heartytrinkets 1.18.2-1.0.0
	- here-be-no-dragons 1.0.0 via twilightforest
	- horseinfo 0.4.1-1.18
	- hydrogen 0.3-SNAPSHOT
	- hyle 0.1.0
	- iceberg 1.0.38
	- impersonate 2.5.0 via requiem
	- incantationem 1.1.3+1.18.2
	- incubus_core 1.7-rc.4 via spectrum
	- indium 1.0.6+mc1.18.2
	- indrev 1.14.0-BETA
	- interference 1.4.1 via redbits
	- iris 1.2.5
	- iron-jetpacks 0.4.3
	- jade 5.99.6
	- jankson 4.0.0+j1.2.0 via libgui
	- java 18
	- javax_annotation_javax_annotation-api 1.3.2 via twilightforest
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- kibe 1.9.8-BETA+1.18
	- kjsextras 3.0.0
	- krypton 0.1.9
	- kubejs 1802.5.4-build.510
	- kubejs_botania 1.0.2
	- kubejs_create 1802.2.2-build.26
	- lazy-language-loader 0.3.0
	- lazydfu 0.1.2
	- libblockattributes_core 0.10.2 via libmultipart_deps_container
	- libblockattributes_fluids 0.10.0 via indrev
	- libblockattributes_items 0.10.0 via indrev
	- libgui 5.4.0+1.18.2 via dark-enchanting
	- libmultipart 0.7.3-pre.4 via libmultipart_deps_container
	- libmultipart_deps_container 0.7.3-pre.4 via wiredredstone
	- libnetworkstack 0.6.0 via libmultipart_deps_container
	- libninepatch 1.1.0 via libgui
	- limitedchunks 1.18.2-2.5
	- lithium 0.7.10
	- locki 0.7.0 via requiem
	- magicalforest 2.0.3
	- magna 1.7.0-1.18-pre1 via indrev
	- mantle 1.18.2-1.9.DEV.02d5091 via tconstruct
	- matrix 1.0.0 via dimdoors
	- mconfig 1.2.0 via extended_drawers
	- megane 7.7.2
	- megane-api 7.7.2 via megane
	- megane-applied-energistics-2 7.7.2 via megane
	- megane-create 7.7.2 via megane
	- megane-extra-generators 7.7.2 via megane
	- megane-fabric-transfer 7.7.2 via megane
	- megane-industrial-revolution 7.7.2 via megane
	- megane-kibe 7.7.2 via megane
	- megane-lib-block-attributes 7.7.2 via megane
	- megane-reborn-core 7.7.2 via megane
	- megane-reborn-energy 7.7.2 via megane
	- megane-runtime 7.7.2 via megane
	- megane-tech-reborn 7.7.2 via megane
	- megane-vanilla 7.7.2 via megane
	- megane-wireless-networks 7.7.2 via megane
	- memoryleakfix 1.18.2-0.3.5
	- midnightlib 0.2.9 via cullleaves
	- milk 0.3.2 via create
	- minecraft 1.18.2
	- mininggadgets ${version}
	- mm 2.3 via buildinggadgets
	- moborigins 1.8.1
	- modern_industrialization 1.2.1
	- moderndynamics 0.2.3-beta
	- modmenu 3.1.1
	- moretags 3.0.4 via the_aether
	- mostructures 1.4.2+1.18.2
	- myron 1.6.2+1.18.1 via golemsgalore
	- ngroklan 1.4.4-1.18
	- noindium 1.0.2+1.18.2 via modern_industrialization
	- notenoughcrashes 4.1.6+1.18.2
	- observable 2.2.3
	- omega-config 1.2.3-1.18.1 via mostructures
	- omega-config-gui 1.2.3-1.18.1 via coxinhautilities
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_jgrapht_jgrapht-core 1.1.0 via dimdoors
	- org_joml_joml 1.10.2 via sodium
	- org_threadly_threadly 6.6 via c2me
	- org_yaml_snakeyaml 1.30 via carpet-tis-addition
	- origins 1.4.1
	- origins-classes 1.3.0
	- owo 0.7.2-no-cme+1.18
	- pandemonium 2.0.0-beta.8
	- pandemoniumapi 2.0.0-beta.8 via pandemonium
	- parry 1.3+1.18
	- patchouli 1.18.2-71.1-FABRIC
	- pehkui 3.3.3+1.14.4-1.19.1
	- placeholder-api 1.1.3+1.17.1 via servercore
	- playerabilitylib 1.5.0 via bewitchment
	- porting_lib 1.1.99999-beta+1.18.2-dev.047a8ad
	- powah 3.0.1-beta
	- precise_armor 1.0
	- probejs 3.1.5
	- progressivebosses 1.0.0
	- promenade 2.6.3
	- reach-entity-attributes 2.2.0 via mantle
	- reborncore 5.2.0
	- recipecache 0.2.1-1.17.1
	- redbits 1.13.3
	- redstonebits 1.8.2
	- reeses-sodium-options 1.4.3+mc1.18.2-build.42
	- refinedstorage2 2.0.0-milestone.1.4
	- refinedstorage2-core-api 2.0.0-milestone.1.4 via refinedstorage2
	- refinedstorage2-grid-api 2.0.0-milestone.1.4 via refinedstorage2
	- refinedstorage2-network-api 2.0.0-milestone.1.4 via refinedstorage2
	- refinedstorage2-resource-api 2.0.0-milestone.1.4 via refinedstorage2
	- refinedstorage2-storage-api 2.0.0-milestone.1.4 via refinedstorage2
	- registrate-fabric MC1.18.2-1.0.3 via create
	- repurposed_structures 4.1.14+1.18.2
	- requiem 2.0.0-beta.9
	- requiem-core 2.0.0-beta.9 via requiem
	- requiemapi 2.0.0-beta.9 via requiem
	- rhino 1802.1.14-build.190
	- roughlyenoughitems 8.3.501
	- rpg_origins 1.0.1
	- sandwichable 1.3+1.18.2
	- satin 1.7.2 via the_aether
	- serialization_hooks 0.2.0+1.18.f5d4aa6 via porting_lib
	- servercore 1.2.9-1.18.2
	- simplevoidworld 4.0.0
	- smart-recipes 0.2.1+1.18.2 via sync
	- smitheesfoundry 1.2.1.1
	- smoke_suppression 1.0.9-1
	- smoothboot 1.18.2-1.7.0
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.5+mc1.18.2-build.42
	- spectrum 1.4.2-1.18.2-chaos_and_exploration
	- spruceui 3.3.0+1.17 via enhancedblockentities
	- star 1.2+1.18.2
	- starlight 1.0.2+fabric.89b8d9f
	- step-height-entity-attribute 1.0.0 via bewitchment
	- subterrestrial 1.0.2
	- sussyconfig 1.0.0 via smitheesfoundry
	- sync 4.2
	- tacocraft 1.7.4-1.18.2
	- tconstruct 1.18.2-3.5.1.DEV.dd9ddc9
	- team_reborn_energy 2.2.0 via reborncore
	- techreborn 5.2.0
	- teenycoal 1.1.3-1.16.x-1.17.x-1.18.x-1.19-snapshot
	- terrablender 1.1.0.102
	- terraform-config-api-v1 3.0.0 via traverse
	- terraform-shapes-api-v1 2.1.0 via promenade
	- terraform-surfaces-api-v1 3.0.0 via traverse
	- terraform-tree-api-v1 3.0.0 via traverse
	- terraform-wood-api-v1 3.0.0 via bewitchment
	- terrarianslimes 1.2.1-BETA+1.18
	- tesseractapi 1.18.2-0.1
	- the_aether 1.6.9+1.18.2
	- the_extractinator 1.0.8
	- travelersbackpack 1.18.2-7.1.2
	- traverse v5.1.0-beta+1.18.2.7f5a8c4
	- traverse-client 5.0.0 via traverse
	- traverse-common 5.0.0 via traverse
	- traverse-worldgen 5.0.0 via traverse
	- trinkets 3.3.1
	- twilightforest 4.1.251
	- upc 0.0.2
	- vmp 0.2.0+beta.3.17
	- waystones 2.5.4
	- wiredredstone 0.3.3+1.18.2
	- wirelessnetworks 1.5.1
	- wthit 4.11.0

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Magnesium

### Searched for known issues?

I did not search

**Comment by AlphaMode** [comment]
The compact is added by twilightforest not tinkers
