### ISSUE TITLE
Buckets don't have dispenser behaviors

### ISSUE THREAD

**Issue by NyakoFox** [Alpha-s-Stuff/TinkersConstruct#20]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.9

### Fabric/Quilt API Version

0.58.0+1.18.2

### Tinkers' Construct Version

1.18.2-3.5.1.DEV.33b3fef

### Describe your issue

The buckets that this mod registers do not have a dispenser behavior. When the buckets are inside of a dispenser and it gets powered, they shoot out like other items, instead of placing the fluid like the built-in buckets.

### Other mods

The modpack is Cabricality.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues

**Comment by AlphaMode** [comment]
Have you checked if this is the same as forge?

**Comment by NyakoFox** [comment]
Apparently it is, which I find odd because I saw images of it working on an older version of the forge mod, [the images found here](https://imgur.com/r/feedthebeast/76LEydf). I'll close the issue since it's the same as forge, however it would be nice to see support for it anyway.

**Comment by NyakoFox** [comment]
reopening as this has been fixed in the forge version (commit https://github.com/SlimeKnights/TinkersConstruct/commit/77b1160d6b2b2962dad051f487e02fba18979a41 issue https://github.com/SlimeKnights/TinkersConstruct/issues/4978)

**Comment by AlphaMode** [comment]
@NyakoFox can you double check this issue the logic in the code seems to checkout not sure if this issue should be closed or not?

**Comment by AlphaMode** [comment]
This works in the current version so I'm just gonna close this
