### ISSUE TITLE
Geodes spawn in the End

### ISSUE THREAD

**Issue by NyakoFox** [Alpha-s-Stuff/TinkersConstruct#22]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.9

### Fabric/Quilt API Version

0.58.0+1.18.2

### Tinkers' Construct Version

1.18.2-3.5.1.DEV.85b8f33

### Describe your issue

Skyslime geodes spawn in the end, which I assume is unintended behavior.

![image](https://user-images.githubusercontent.com/87289390/185285600-778f0bdc-6a73-4af5-b7cf-6fd485d1d98a.png)

### Other mods

The modpack is Cabricality

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues

**Comment by NyakoFox** [comment]
This does seem to be unintended since this does not happen in the forge version.

**Comment by JieningYu** [comment]
Also they will generate in the space from Ad Astra mod.
