### ISSUE TITLE
Common tags aren't adjusted for fabric

### ISSUE THREAD

**Issue by NyakoFox** [Alpha-s-Stuff/TinkersConstruct#23]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.9

### Fabric/Quilt API Version

0.58.0+1.18.2

### Tinkers' Construct Version

1.18.2-3.5.1.DEV.85b8f33

### Describe your issue

![image](https://user-images.githubusercontent.com/87289390/185702870-bbacb21d-3253-4bfe-9137-49978d5b8bd2.png)

In Fabric, the common tag for Iron Dust is `c:iron_dusts`. However, Forge uses a system like `c:dusts/iron`. This means that by default, this port does not work with modded items in recipes. It would be very helpful if the json files were adjusted to use the Fabric tags, since this is a Fabric port.

[I'm sure you already know about this page, but here's a list of Fabric common tags.](https://fabricmc.net/wiki/tutorial:tags)

### Other mods

![image](https://user-images.githubusercontent.com/87289390/185703473-53ea7524-13f9-469a-9d47-26f6e47e131e.png)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by AlphaMode** [comment]
This isn't going to change. If you want compatibility with other mods you can use a KubeJS script to unify tags. Like AOF5 does

**Comment by NyakoFox** [comment]
Can I ask why though?

**Comment by AlphaMode** [comment]
https://github.com/FabricMC/fabric/issues/2186 issue is I don't like the current standard it's hard to navigate and clunky. My overall the goal is to get more mods to use this convention as it's just more organized and makes things easier to maintain for multi loader mods. As I said if your making a modpack I suggest you just use AOF5's unification script.

**Comment by NyakoFox** [comment]
I'm not making a modpack, it's just something I noticed. Thank you for linking me to this issue, I'm in support of the convention change so it's nice to know people are actually doing something about it.
