### ISSUE TITLE
Missing Ability/Modifier

### ISSUE THREAD

**Issue by SPKChaosPhoenix** [Alpha-s-Stuff/TinkersConstruct#26]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.9

### Fabric/Quilt API Version

0.58.0+1.18.2

### Tinkers' Construct Version

build 147

### Describe your issue

The Luck Modifier (which is pressent in the Forge version) is missing.

### Other mods

I tried it with no other mods and with the All of Fabric Modpack

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by AlphaMode** [comment]
![image](https://user-images.githubusercontent.com/26313415/189449023-f41e47b0-af17-4a37-8da7-e13a278f4de2.png)
I can't seem to reproduce this

**Comment by SPKChaosPhoenix** [comment]
After some more testing i can conclude, that the Mod [Enchancement](https://www.curseforge.com/minecraft/mc-mods/enchancement) is the source for my trouble.
Apperently my Moddles instalation wasn`t as modless as i thought.... mb
