### ISSUE TITLE
Can't transfer fluid using Create's pipe

### ISSUE THREAD

**Issue by JieningYu** [Alpha-s-Stuff/TinkersConstruct#3]
### Minecraft Version

1.18.2

### Forge Version

what is froge

### Mantle Version

1.9dev(jar in jar)

### Tinkers' Construct Version

3d8db7eDEV1.18.2

### Describe your issue

as the title says, can't transfer fluid between Tconstruct's fluid containers using Create's fluid pipes.
Also can't use a empty bucket or fluid bucket on a Seared Drain to put fluid into smeltry by hand.

### Crash Report

no

### Other mods

Create 0.5
Fabric API
Sodium
Lithium
Starlight

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by AlphaMode** [comment]
I wouldn't try transfering between mods as everything is still using milibuckets right now
I will switch things over to droplets when I get data gen working

**Comment by JieningYu** [comment]
There's another issue caused by tconstruct itself(maybe) that can't use a empty bucket or fluid bucket on a Seared Drain

**Comment by AlphaMode** [comment]
Have you checked to see if its like that on forge?

**Comment by JieningYu** [comment]
No.

**Comment by JieningYu** [comment]
> Have you checked to see if its like that on forge?

As far as I know, it works under forge.

**Comment by moechakucha** [comment]
> As long as I know, it works under forge.

Isn't this "as far as I know"?

**Comment by JieningYu** [comment]
> > As long as I know, it works under forge.
> 
> Isn't this "as far as I know"?

bruh
stupid me

**Comment by JieningYu** [comment]
Still can't transfer fluid after using droplets

**Comment by JieningYu** [comment]
<img width="264" alt="image" src="https://user-images.githubusercontent.com/61787533/182520107-3434f3c3-5364-49f0-ad66-c38ee9fd358f.png">
