### ISSUE TITLE
Kama does not shear animals

### ISSUE THREAD

**Issue by Linguardium** [Alpha-s-Stuff/TinkersConstruct#31]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

Fabric 0.14.10

### Fabric/Quilt API Version

0.59.0

### Tinkers' Construct Version

3.5.2.150

### Describe your issue

The Kama does not allow shearing of sheep. 

The description of the tool mentions shearing animals.
right click on sheep shows success, but no shearing happens.

forge tinkers does allow shearing of animals, and the clientside success of right click appears that it should function, so this appears to be a bug.

### Other mods

None. Tested issue with Hephaestus and FApi alone

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by AlphaMode** [comment]
Thanks for reporting this I'll have a new release out soon!
