### ISSUE TITLE
[Compat] BYG Woods and Stones cannot be used as materials

### ISSUE THREAD

**Issue by shanoaice** [Alpha-s-Stuff/TinkersConstruct#32]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

Quilt 0.17.6

### Fabric/Quilt API Version

QFAPI-1.0.0-beta.26+0.59.1-1.18.2

### Tinkers' Construct Version

1.18.2-3.5.2.150

### Describe your issue

None of Oh The Biomes You'll Go woods or stones were able to be used as tool materials.

### Other mods

- Oh The Biomes You'll Go

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by AlphaMode** [comment]
In order for BYG to support Hephaestus they need to add their materials to the tags we use such as c:rods/wooden
