### ISSUE TITLE
convention tags

### ISSUE THREAD

**Issue by rlnt** [Alpha-s-Stuff/TinkersConstruct#36]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

/

### Fabric/Quilt API Version

/

### Tinkers' Construct Version

/

### Describe your issue

Why does every mod you guys make for Fabric use Forge-styled tags?

If you really want to take great Forge mods and port them to Fabric, please do it in a proper way.
It makes it incredibly annoying to work with.

Create Fabric has the same problem, which has been ignored for a while and was supposed to be changed in 1.19, but it's still there.
https://github.com/Fabricators-of-Create/Create/issues/162

This is not a valid answer: https://github.com/Alpha-s-Stuff/TinkersConstruct/issues/23#issuecomment-1221076200

If you want to make money porting mods from another loader, use the loader's conventions and don't be stubborn about a tag format you may not like. It's not conducive to clean modding compatibility and the community if you just act selfishly.

Telling people to change it themselves via KubeJS just shows you don't care and just want to grab the money.
I also prefer Forge-styled tags as they make more sense, but that's no reason to go against the flow until the loader convention changes.

Instead, try to convince the people who make the loader, and stop pressuring players and pack developers for your own benefit and laziness.

### Crash Report

/

### Other mods

/

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by AlphaMode** [comment]
I'm not even do this for the money and I dont even use my curseforge points for anything. If I am being selfish about this then so be it. I've already stated I'm not changing the convention a compatability layer has already been discussed and is being worked on.

**Comment by AlphaMode** [comment]
I should also note that I've already tried to mention this to fabric https://github.com/FabricMC/fabric/issues/2186
