### ISSUE TITLE
Searching in JEI

### ISSUE THREAD

**Issue by Kamiszewskyy** [Alpha-s-Stuff/TinkersConstruct#38]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.12

### Fabric/Quilt API Version

0.67.0

### Tinkers' Construct Version

 Hephaestus-1.18.2-3.5.2.155.jar

### Describe your issue

Minecraft crashes when searching something in JEI. I don't know what it really is.

### Crash Report

https://hastebin.skyra.pw/zexiqoneka.yaml

### Other mods

In the crash report file

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues

**Comment by AlphaMode** [comment]
Your log link isn't valid, jei support has been disabled in latest release and is not likely to come back. I suggest you use rei
