### ISSUE TITLE
Soulbound modifier not working

### ISSUE THREAD

**Issue by Skunkynator** [Alpha-s-Stuff/TinkersConstruct#39]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.17.8

### Fabric/Quilt API Version

0.67.0-1.18.2

### Tinkers' Construct Version

1.18.2-3.5.2.155

### Describe your issue

When dying with a soulbound item, the item drops instead of being kept in the inventory, like the description suggests.

### Other mods

Cabricallity modpack, but tested with just tinkers.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by BleachKing919** [comment]
Was a fix ever found for this, as I am having the same issue.

**Comment by AlphaMode** [comment]
No, I haven't fixed any issues in a while
