### ISSUE TITLE
Step-Assist Modifier (I or II) not working

### ISSUE THREAD

**Issue by rcshort** [Alpha-s-Stuff/TinkersConstruct#44]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.14

### Fabric/Quilt API Version

0.67.1+1.18.2

### Tinkers' Construct Version

1.18.2-3.5.2.150

### Describe your issue

After applying Step Up 1 to my leggings, I was still unable to walk onto blocks as if they were stairs.

The "Step Up I" tag is present on my leggings, but the details show a reference to porting_lib.
![image](https://user-images.githubusercontent.com/13852945/221374517-7945a292-388a-4729-9d4f-4d25b4ba7ced.png)

After researching, this might extend to that library.

Although I didn't test in an instance with just this mod, I did see this issue present in another modpack.

### Other mods

![image](https://user-images.githubusercontent.com/13852945/221374627-80b3c104-8186-4dbf-b160-b4474c38622a.png)
![image](https://user-images.githubusercontent.com/13852945/221374636-2b693761-8058-47c6-8a2e-43c3193b94b7.png)
![image](https://user-images.githubusercontent.com/13852945/221374647-3ba09f56-5508-42df-858a-65c94f8c9b7e.png)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KonSola5** [comment]
A solution would be to change the attribute to `"stepheightentityattribute:stepheight"`, and depend on [step-height-entity-attribute](https://github.com/emilyploszaj/step-height-entity-attribute).

**Comment by AlphaMode** [comment]
Porting Lib already has the attribute so no that wouldn't help, and it would only cause issues for existing worlds. I am going to be fixing most issues once 1.19 is ready, except that might be a while due to upstream wanting to stick to 1.18.2 for a while

**Comment by KonSola5** [comment]
So it's up to Porting Lib to fix its Step Height attribute?

**Comment by AlphaMode** [comment]
It's probably already fixed on 1.19.3, jay is the only one who still maintains 1.18.2 porting lib.

**Comment by KonSola5** [comment]
Anyway, modpacks can implement this fix by themselves using a datapack (TConstruct is seriously flexible these days)

**Comment by AlphaMode** [comment]
Fixed in latest commit
