### ISSUE TITLE
FTB Ultimine compat 

### ISSUE THREAD

**Issue by LyonGalaxy** [Alpha-s-Stuff/TinkersConstruct#45]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.14

### Fabric/Quilt API Version

0.67.1

### Tinkers' Construct Version

3.5.2.150

### Describe your issue

Tried using a Tinkers Pickaxe with FTB Ultimine. When holding down the grave key, Ultimine says how many blocks will be broken, however only the block you are looking at is broken, not the rest of them

### Other mods

Create: Astral v2.0.3. FTB Ultimine version 1802.3.3-build.70

### Tried reproducing with just Tinkers?

I will go do that now

### Performance Enchancers

Sodium

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by AlphaMode** [comment]
Install https://www.curseforge.com/minecraft/mc-mods/tamago if you want compatibility

**Comment by LyonGalaxy** [comment]
> Install https://www.curseforge.com/minecraft/mc-mods/tamago if you want compatibility

Thank u i love u <3
