### ISSUE TITLE
[1.18.2] Tasty trait doesn't work

### ISSUE THREAD

**Issue by KonSola5** [Alpha-s-Stuff/TinkersConstruct#48]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.14

### Fabric/Quilt API Version

v0.67.1+1.18.2

### Tinkers' Construct Version

v1.18.2-3.5.2.150

### Describe your issue

You can't eat tools with Pig Iron Parts.

To reproduce:
1. Grab any tool with at least 1 Pig Iron part,
2. Make yourself hungry,
3. Try to eat it.

There are eating particles and sound effects, however:
1. There's no animation (is this also the case in Tinker's Construct?)
2. You can't eat it at all, no matter how long you hold the right click button.

### Other mods

Modpack: Create Astral

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by AlphaMode** [comment]
Works fine in 1.19.4
