### ISSUE TITLE
kama doesnt work

### ISSUE THREAD

**Issue by AnAwesomGuy** [Alpha-s-Stuff/TinkersConstruct#52]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.14

### Fabric/Quilt API Version

0.76.0+1.18.2

### Tinkers' Construct Version

1.18.2-3.5.2.155

### Describe your issue

kamas can shear animals, but do not shear grass and such

### Other mods

[mods.txt](https://github.com/Alpha-s-Stuff/TinkersConstruct/files/11238142/mods.txt)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by AlphaMode** [comment]
Fixed in https://github.com/Alpha-s-Stuff/TinkersConstruct/commit/f82b666afbc39960e6704536b231df2726e5e21d
