### ISSUE TITLE
Ticking Block Entity crash

### ISSUE THREAD

**Issue by ghost** [Alpha-s-Stuff/TinkersConstruct#53]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

14.19

### Fabric/Quilt API Version

76.0-1.18.2

### Tinkers' Construct Version

1.18.2-3.5.2.155

### Describe your issue

When joing the server the server instantly crashes.

before the crash i was messing with the smelter and I put in Iron copper zinc (from create) and gold in that order. then started poring the iron into iron blocks in casting bins. then the server crashed and was then unobtainable

### Crash Report

https://mclo.gs/9lji4pm

### Other mods

        - architectury 4.11.90
	- badpackets 0.1.3
	- balm-fabric 3.2.6
	- bbs 1.0.0
	- bclib 1.4.7
	- bettercombat 1.6.2+1.18.2
	- betterdeserttemples 1.18.2-Fabric-1.3.1
	- betterdungeons 1.18.2-Fabric-2.1.0
	- betterend 1.1.1
	- betterfortresses 1.18.2-Fabric-1.0.0
	- bettermineshafts 1.18.2-Fabric-2.2
	- betteroceanmonuments 1.18.2-Fabric-1.0.3
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- bookshelf 13.2.53
	- byg 1.4
	- cardinal-components 4.2.0
	- charm 4.4.4
	- cloth-config 6.3.81
	- collective 6.53
	- comforts 1.1.3-1.18.2
	- cosmetic-armor 1.3.1
	- create 0.5.0.i-988+1.18.2
	- createplus 1.0
	- crittersandcompanions 1.18.2-1.0.2
	- dawn 3.3.2
	- drg_flares 1.2.1
	- easymagic 3.3.0
	- emi 0.7.3+1.18.2
	- emi_loot 0.6.1+1.18.2
	- emotecraft 2.2.7-b.build.48
	- endrem 5.1.0
	- exlinecopperequipment 2.1.1
	- expandeddelight 0.1.9.1
	- extra 1.0.0
	- extraorigins 1.18-12
	- fabric-api 0.76.0+1.18.2
	- fabric-language-kotlin 1.9.3+kotlin.1.8.20
	- fabricloader 0.14.19
	- fallingtree 3.5.4
	- farmersdelight 1.18.2-1.2.5
	- farmersknives 1.3.1
	- ferritecore 4.2.1
	- forgeconfigapiport 3.2.4
	- friendsandfoes 1.4.7
	- geckolib3 3.0.80
	- gildedarmor 1.4.2+fabric-1.18.2
	- gravestones v1.11.1
	- grindenchantments 1.6.4+1.18.2
	- hookshot 25.0
	- horsebuff 2.0.1
	- iceberg 1.0.38
	- interactic 0.1.10+1.18
	- itemblacklist 1.18.2-1.2.1
	- java 17
	- kiwi 6.0.2
	- lazydfu 0.1.2
	- libjf 2.8.1
	- lithium 0.10.3
	- magiclib 0.7.293+17aa28c-stable
	- mca 7.4.8+1.18.2
	- memoryleakfix 1.0.0
	- midnightlib 0.4.4
	- minecraft 1.18.2
	- mixintrace 1.1.1+1.17
	- naturescompass 1.18.2-2.0.3-fabric
	- netherportalfix 9.0.1
	- nogizmo 1.5
	- observable 2.2.3
	- origins 1
	- origins-classes 1.3.0
	- peacefulsurface 1.18.2-v1-fabric
	- pehkui 3.7.3+1.14.4-1.20
	- player-animator 1.0.2+1.18
	- polymorph 0.0.21-1.18.2
	- puzzleslib 3.3.5
	- ratsmischief 1.3.7
	- retraining 1.1.0
	- servercore 1.2.9-1.18.2
	- simple_backpack 1.2.37
	- simple_shelves 1.0.7
	- simplyswords 1.40-1.18.2
	- smallernetherportals 3.4
	- smallships 2.0.0a1.1.1
	- smoke_suppression 1.0.9-1
	- smoothchunk 1.18.2-1.9
	- snowundertrees 1.0.0+1.18.2
	- spiderstpo 1.18.2-2.0.2
	- stackrefill 4.0
	- starlight 1.0.2+fabric.89b8d9f
	- structory 1.0.0
	- tconstruct 1.18.2-3.5.2.155
	- terrablender 1.2.0.126
	- toms_storage 1.5.2
	- tradingpost 3.2.0
	- transparent_cosmetics 1.4.0
	- trinkets 3.3.1
	- universal_ores 1.3.1
	- vanillatweaks 1.5.58
	- vinery 1.1.4
	- voicechat 1.18.2-2.4.4
	- walllanterns 1.3.0-1.18.x
	- wthit 4.13.6
	- xaerominimap 23.4.0
	- xaeroworldmap 1.30.0
	- yungsapi 1.18.2-Fabric-2.2.9
	- yungsbridges 1.18.2-Fabric-2.1.0
	- yungsextras 1.18.2-Fabric-2.1.0

### Tried reproducing with just Tinkers?

I will go do that now

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ghost** [comment]
Seems to be a issue with create and making alloys

**Comment by CoderXL1** [comment]
Check this out:
Fuzss/puzzleslib#91
It's puzzleslib.

**Comment by AlphaMode** [comment]
Should be fixed in latest
