### ISSUE TITLE
Hephasteus not compatible with ftb ultimine 

### ISSUE THREAD

**Issue by CapToad** [Alpha-s-Stuff/TinkersConstruct#54]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.19 Fabric

### Fabric/Quilt API Version

0.76.0 Fabric Api

### Tinkers' Construct Version

3.5.2.155 1.18.2

### Describe your issue

Hephasteus tools aren't compatible with ftb ultimine (tools from other mods work) idk if other vein miner mods also have this issue

### Other mods

Create Astral v2.0.4c (ftb ultimine added manually)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues

**Comment by AlphaMode** [comment]
You need tamago if you want compatibility https://modrinth.com/mod/tamago

**Comment by BamsyTheSergal** [comment]
> You need tamago if you want compatibility https://modrinth.com/mod/tamago

this no longer works anymore. it causes startup crashes. there is no real place for this specific mod for me to ask for help.
