### ISSUE TITLE
Raised mod incompatability

### ISSUE THREAD

**Issue by TheStaticVoid** [Alpha-s-Stuff/TinkersConstruct#57]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.19

### Fabric/Quilt API Version

0.76.0+1.18.2

### Tinkers' Construct Version

3.5.2.155

### Describe your issue

When using the mod [Raised](https://modrinth.com/mod/raised), a popular mod to fix a hotbar bug, the heart containers seem to stick to their original position when Hepheastus is installed.

The test instance I used only used the mods listed below, which are the dependencies, Hephaestus, and Raised, with nothing else.

![image](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/6089108/354e4c25-0599-4fb9-8108-4688997422ac)

### Other mods

Architectury
Cloth Config
Fabric API
Fabric Language Kotlin
Hephaestus
Raised

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by HaXrDEV** [comment]
Should maybe also post on the repo for Raised, as they have fixed similar issues on their end before.

**Comment by AlphaMode** [comment]
https://github.com/Alpha-s-Stuff/Mantle/commit/a8f3c6a52aafc4ad0382266e082c4ccebb2dd51c Fixed in this commit will be publicly available next release.
