### ISSUE TITLE
Memory leak in CopperCanModel

### ISSUE THREAD

**Issue by mspielberg** [Alpha-s-Stuff/TinkersConstruct#59]
### Minecraft Version

1.18.2

### Fabric Version

0.76.0-1.18.2

### Hephaestus Version

1.18.2-3.5.2.155

### Describe your issue

Due to Fabricators-of-Create/Porting-Lib#50, the [cache in CopperCanModel](https://github.com/Alpha-s-Stuff/TinkersConstruct/blob/1.19.4/src/main/java/slimeknights/tconstruct/smeltery/client/CopperCanModel.java#L160) grows without bound, eventually exhausting memory.

Reporting here as well in case you want to fix or work around the issue within Hephaestus as an interim fix until Porting-Lib is fixed.

### Other mods

Experienced with [Create Astral](https://github.com/Laskyyy/Create-Astral) ([CurseForge](https://www.curseforge.com/minecraft/modpacks/create-astral/files/4496625) v2.0.4c.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by AlphaMode** [comment]
Will be fixed next release

**Comment by AlphaMode** [comment]
Fixed in later versions. A 1.18.2 backport in Porting-Lib will probably be done later.
