### ISSUE TITLE
[Compat] Inventory Tabs

### ISSUE THREAD

**Issue by sleepingdragoninn** [Alpha-s-Stuff/TinkersConstruct#6]
### Minecraft Version

1.18.1

### Forge Version

Quilt 0.17.1-beta6 (lol)

### Mantle Version

N/A

### Tinkers' Construct Version

3.5.1.DEV.04887b6

### Problem description

When opening a UI such as the part builder or tinker's station, the cursor centers on the window. This is normal behvaviour for vanilla, but with [Inventory Tabs](https://modrinth.com/mod/inventory-tabs-updated) it becomes an inconvenience with seemingly an easy fix.

https://user-images.githubusercontent.com/55819817/180699729-f3a1a323-3994-4daa-94f5-2d61e0f14c19.mp4

)

### Suggested solution

Don't center the cursor, or, find out why the cursor is being centered in the first place (forcing itself to close and reopen the screen maybe?)

### Alternatives considered

Honestly if it's too hardbasket I just wouldn't do it.

### Searched for existing enhancement?

Used the search bar

**Comment by sleepingdragoninn** [comment]
This behaviour is of course identical on forge as far as I'm aware, but inventory tabs isn't on forge from what I can tell! If anyone can find an equivalent forge mod that would also cause an issue due to this, feel free to drop the issue upstream.

**Comment by sleepingdragoninn** [comment]
Lmao I _just_ figured out that tinker's has this "tabbing" behaviour in-built, which is probably what controls this
(pictured without inventory tabs)
![image](https://user-images.githubusercontent.com/55819817/180931548-e9c62f76-ccd6-4ae4-98e5-14f68024e705.png)

Would be good to handle this case and defer to InventoryTabs (disabling tinker's tabs) if possible.

**Comment by AlphaMode** [comment]
> Lmao I _just_ figured out that tinker's has this "tabbing" behaviour in-built, which is probably what controls this (pictured without inventory tabs) ![image](https://user-images.githubusercontent.com/55819817/180931548-e9c62f76-ccd6-4ae4-98e5-14f68024e705.png)
> 
> Would be good to handle this case and defer to InventoryTabs (disabling tinker's tabs) if possible.

I'm pretty sure that would just break tinkers since I'm pretty sure the tabs code is handled on the client and server. I think inventory tabs is all on client. So I see some possible problems there but I'd be glad to accept a pr that adds support though

**Comment by sleepingdragoninn** [comment]
I think it's handleable - the tab code on the server side doesn't need to change, it's only the physical clickable client-side tabs themselves that need to be hidden from the screen that's being shown, such that they don't overlap with IT's. I'll give it a think at some point.

**Comment by sleepingdragoninn** [comment]
ahahah yeah I saw the commit - I'll redo the PR no problem - feel free to
ditch what we put in
