### ISSUE TITLE
Target 1.19.2

### ISSUE THREAD

**Issue by rinebergc** [Alpha-s-Stuff/TinkersConstruct#62]
### Minecraft Version

1.19.2

### Fabric Version

0.14.21-1.19.2

### Mantle Version

N/A

### Hephaestus Version

N/A

### Problem description

TC is currently incompatible with 1.19.2.

### Suggested solution

Create a build targeting 1.19.2.

### Alternatives considered

N/A

### Searched for existing enhancement?

Used the search bar

**Comment by AlphaMode** [comment]
1.19.2 is not planned
