### ISSUE TITLE
Crashes with Pehkui mod

### ISSUE THREAD

**Issue by naiyQAQ** [Alpha-s-Stuff/TinkersConstruct#63]
### Minecraft Version

1.19.4

### Fabric/Quilt Version

0.14.21

### Fabric/Quilt API Version

0.86.1-1.19.4

### Hephaestus Version

1.19.4-3.6.3.212

### Describe your issue

I can't launch game with pehkui installed.
I tried to remove all mods except Hephasetus and Pehkui, but the issue still

### Crash Report

https://pastebin.com/cUKYGmgT

### Other mods

Pehkui 3.7.2~3.7.7 all tried

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by naiyQAQ** [comment]
Touch by mistake

**Comment by AlphaMode** [comment]
Should be fixed in the 1.20.1 version I can possibly look into backporting it to 1.19.4 later
