### ISSUE TITLE
[1.20.1]Server Startup Failure: Conflict between Hephaestus and Create leading to NoClassDefFoundError

### ISSUE THREAD

**Issue by windy664** [Alpha-s-Stuff/TinkersConstruct#64]
### Minecraft Version

1.20.1

### Fabric/Quilt Version

0.14.22

### Fabric/Quilt API Version

0.87

### Hephaestus Version

1.20.1-3.6.3.222

### Describe your issue

When both Hephaestus and Create mods are present, the server fails to start due to a NoClassDefFoundError. Specifically, Hephaestus is attempting to access a class from the Create mod (io/github/fabricators_of_create/porting_lib/entity/events/LivingEntityEvents) which it cannot find, leading to a server crash.
https://github.com/Fabricators-of-Create/Create/issues/1061
### Crash Report

https://github.com/Fabricators-of-Create/Create/files/12385245/latest.log

### Other mods

Create

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

I did not search

**Comment by gundami** [comment]
i have the same problem. is there any process?

**Comment by AkashiiKun** [comment]
![Screenshot_2023-09-01-21-14-29-15_572064f74bd5f9fa804b05334aa4f912](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/44606942/74296eaf-e8db-4157-8a5c-79ec8c028f4e)

**Comment by bananaOHHHOOOOHAHAHAHAAAAHA** [comment]
> ![Screenshot_2023-09-01-21-14-29-15_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/44606942/265417894-74296eaf-e8db-4157-8a5c-79ec8c028f4e.jpg)

will they try to fix it for 1.20.1? i really need it for this modpack im making but if they cant fix it then thats ok

**Comment by stopmotio** [comment]
Would that fix also be released for 1.20.1? I was really looking forward to this mod

**Comment by broccoder** [comment]
> i have the same problem. is there any process?

Yes, you can use this fork of create as a workaround: https://github.com/DM-Earth/create-fabric-dme-edition
