### ISSUE TITLE
[1.20.1]incompatibility between Sodium 0.5 and TC

### ISSUE THREAD

**Issue by Hophenby** [Alpha-s-Stuff/TinkersConstruct#65]
### Minecraft Version

1.20.1

### Fabric/Quilt Version

0.14.22

### Fabric/Quilt API Version

0.87.0-1.20.1

### Hephaestus Version

1.20.1-3.6.3.222

### Describe your issue

crash with sodium 0.5.2 when entering world
here is the crash report:
[crash-2023-08-22_23.39.35-client.txt](https://github.com/Alpha-s-Stuff/TinkersConstruct/files/12410418/crash-2023-08-22_23.39.35-client.txt)

here is the latest log:
[latest.log](https://github.com/Alpha-s-Stuff/TinkersConstruct/files/12410413/latest.log)

### Crash Report

https://github.com/Alpha-s-Stuff/TinkersConstruct/files/12410418/crash-2023-08-22_23.39.35-client.txt

### Other mods

sodium-fabric-mc1.20.1-0.5.2

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

Checked pinned issues

**Comment by AlphaMode** [comment]
Fixed in latest release https://modrinth.com/mod/hephaestus/version/1.20.1-3.6.3.231
