### ISSUE TITLE
[1.20.1] Hephaestus 3.6.3.222 crash with sodium 0.4.10

### ISSUE THREAD

**Issue by CGMejia2001** [Alpha-s-Stuff/TinkersConstruct#66]
### Minecraft Version

1.20.1

### Fabric/Quilt Version

0.14.22

### Fabric/Quilt API Version

0.87.0-1.20.1

### Hephaestus Version

3.6.3.222

### Describe your issue

Crashes with sodium 0.4.10, seems like when using the drain on a casting table right after fluid drops from the faucet it crashes the game.  tested with a bunch of client side mods but mostly library and api mods 

### Crash Report

https://gist.github.com/HaizUber/f4c1e41d805046cbc29a8399bfb265b5

### Other mods

3d skin layers
architectury api
balm
bclib
botarium
cloth config
collective
creative core
cristel lib
fabric languange kotlin
forge config api port
geckolib
icebeerg
indium
iris
lets do api
library ferret
midnight lib
m.r.u (mineblock repeated utilities)
mod menu
moonlight
more axolotl variants api
obscure api
player animator
prism
puzzles lib
resourceful config and lib
runes
sodium
spell engine
spell power attribute
supermartijn642's config lib and core lib
trinkets
yetanotherconfiglib

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues

**Comment by AlphaMode** [comment]
https://modrinth.com/mod/hephaestus/version/1.20.1-3.6.3.231 works with sodium 0.5.2 as long as you have indium
