### ISSUE TITLE
Crash when scrolling through Tinkers' Smeltery creative tab

### ISSUE THREAD

**Issue by jakeismyname** [Alpha-s-Stuff/TinkersConstruct#67]
### Minecraft Version

1.20.1

### Fabric/Quilt Version

Quilt: 0.20.2 Fabric: 0.14.22

### Fabric/Quilt API Version

Quilt: 7.2.1+0.88.0 Fabric: 0.88.1

### Hephaestus Version

1.20.1-3.6.3.229

### Describe your issue

Game crashes when trying to render a block in the Tinkers' Smeltery creative tab, towards the bottom of the tab.
Crashes on Quilt and Fabric, regardless of Sodium+Indium being present.

### Crash Report

https://mclo.gs/IdFLDqE

### Other mods

Just Hephaestus and Fabric API

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by AlphaMode** [comment]
Why is it always wrapped models :pain:

**Comment by AlphaMode** [comment]
I believe this was already fixed in the next action build https://github.com/Alpha-s-Stuff/TinkersConstruct/actions/runs/6067063434

**Comment by AlphaMode** [comment]
Should be fixed in latest release https://modrinth.com/mod/hephaestus/version/1.20.1-3.6.3.231
