### ISSUE TITLE
Right click interactions don't work on most tools

### ISSUE THREAD

**Issue by sleepingdragoninn** [Alpha-s-Stuff/TinkersConstruct#7]
### Minecraft Version

1.18.2

### Fabric Version

Quilt 0.17.1-beta.6

### Fabric API Version

QSL 1.0.0-beta.22+0.56.0-1.18.2

### Tinkers' Construct Version

3.5.1.DEV.04887b6

### Describe your issue

Just posting a general issue to cover most of the right click interactions not working.

I'm assuming it's pretty much everything, but offhand daggers don't work, and mattocks don't work (and seemingly interact with everything)

### Other mods

QSL + TCon, confirmed.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by InspectorBoat** [comment]
This issue has not been fixed; Offhand daggers still do not work.
