### ISSUE TITLE
[1.20.1] All Scorched/Seared Duct/Drain/Chute variants render as a brick variant in the world

### ISSUE THREAD

**Issue by KonSola5** [Alpha-s-Stuff/TinkersConstruct#71]
### Minecraft Version

1.20.1

### Fabric Version

0.89.3+1.20.1

### Hephaestus Version

1.20.1-3.6.3.232

### Describe your issue

The Smeltery/Foundry IO block variants do render differently in inventory, in hand and as a dropped item:
![inv](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/125081901/d4845030-5a46-4393-be68-85949191f342)
... but they all do render as a brick variant in-world.
![world](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/125081901/1a14a0d5-abe9-4cc0-a191-b8b421cfa4ec)

### Other mods

- architectury-9.1.12-fabric
- cloth-config-11.1.106-fabric
- fabric-api-0.89.3+1.20.1
- fabric-language-kotlin-1.10.10+kotlin.1.9.10
- Hephaestus-1.20.1-3.6.3.232
- indium-1.0.27+mc1.20.1
- NoChatReports-FABRIC-1.20.1-v2.2.2
- RebornCore-5.8.7
- RoughlyEnoughItems-12.0.665
- sodium-fabric-mc1.20.1-0.5.3
- TechReborn-5.8.7

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by AlphaMode** [comment]
Should be fixed in https://modrinth.com/mod/hephaestus/version/1.20.1-3.6.3.240
