### ISSUE TITLE
[1.20.1] Incompatible with WorldEdit mod

### ISSUE THREAD

**Issue by JMackey1** [Alpha-s-Stuff/TinkersConstruct#77]
### Minecraft Version

1.20.1

### Fabric/Quilt Version

0.14.22

### Fabric/Quilt API Version

0.89.3+1.20.1

### Hephaestus Version

1.20.1-3.6.3.232

### Describe your issue

When Hephaestus and WorldEdit mods are both enabled, worlds will get stuck on loading. To be clear, there is no crash, and the game loads - it's just that a world will not start up. This can be a new world or an existing one. When I disabled WorldEdit, and made no other changes or disable any other mods, worlds loaded correctly and I could see Hephaestus items in REI.

However, when I disable all mods other than Hephaestus, WorldEdit and Fabric API, everything loads correctly. So, while disabling WorldEdit makes the game load with Hephaestus, it seems there is some inter-mod issue outside of WorldEdit that causes the combination to not work... But, when I disable Hephaestus and have WorldEdit enabled, and all other mods enabled, worlds also load correctly. So it's something like WorldEdit + Hephaestus + x, where I have no idea what x is.

### Other mods

Huge list, see link: https://pastebin.com/C8vM9qA1

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium, Other (specify under other mods)

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by JMackey1** [comment]
I did some additional testing yesterday. The 3rd problematic mod seems to be Diagonal Windows. Info below:

The problematic 3rd mod seems to be Diagonal Windows. Test cases below:

    All mods from my pastebin enabled - worlds will not load
    All mods from my pastebin enabled, except Hephaestus disabled - worlds will load
    All mods from my pastebin enabled, except WorldEdit disabled - worlds will load
    All mods from my pastebin enabled, except Diagonal Windows disabled (so Hephaestus and WorldEdit are enabled) - worlds will load
    All mods from my pastebin disabled, except Fabric API, WorldEdit, and Hephaestus enabled - worlds will load
    All mods from my pastebin disabled, except Fabric API, WorldEdit, Hephaestus, Diagonal Windows, Forge Config API Port (dependency for Diagonal Windows), and Puzzles Lib (dependency for Diagonal Windows) enabled - game won't load, can't even get to world screen (no idea why the subset behaves like this but game loads with all mods enabled...)
    All mods from my pastebin disabled, except Fabric API, WorldEdit, Hephaestus, Forge Config API Port, and Puzzles Lib enabled (no Diagonal Windows but its dependencies) - worlds will load

Other mod versions:
Puzzles Lib - 8.0.24
Forge Config API Port - 8.0.0
Diagonal Windows - 8.0.1

Let me know if you need additional information. I'm going to provide this information to the Diagonal Windows Github as well.

**Comment by AlphaMode** [comment]
Can you please provide your log files? Saying your world won't load is a bit vague

**Comment by JMackey1** [comment]
[latest.log](https://github.com/Alpha-s-Stuff/TinkersConstruct/files/12917934/latest.log)

**Comment by AlphaMode** [comment]
So I look around some issues and it seems the problem was Star? I'm not 100% sure, but it should be fixed in the latest version.
