### ISSUE TITLE
[GitHub] Update issue and enhancement templates to 1.20.1

### ISSUE THREAD

**Issue by KonSola5** [Alpha-s-Stuff/TinkersConstruct#80]
### Minecraft Version

1.20.1

### Fabric Version

0.89.3+1.20.1

### Mantle Version

1.20.1-1.9.254

### Hephaestus Version

1.20.1-3.6.3.232

### Problem description

Current templates for issues are made for 1.19.4 version of Hephaestus, despite newest versions of that mod being on 1.20.1.

### Suggested solution

- Update the auto-filled info in the text boxes to the current Hephaestus version (shown at the beginning of this enhancement issue).
- Remove the 1.18 templates since 1.18.2 and 1.19.4 versions of Hephaestus are no longer supported.
- Remove the "Mantle Version" from the template since Hephaestus is bundled with Mantle.

### Alternatives considered

None.

### Additional context

.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by AlphaMode** [comment]
Fixed
