### ISSUE TITLE
[Suggestion] Option to disable increasing modifier/ability slots

### ISSUE THREAD

**Issue by cybercat5555** [Alpha-s-Stuff/TinkersConstruct#84]
### Minecraft Version

1.20.1

### Fabric Version

0.21.0

### Fabric API Version

qfapi-7.4.0_qsl-6.1.2_fapi-0.90.0_mc-1.20.1

### Hephaestus Version

Hephaestus-1.20.1-3.6.3.232

### Describe your issue

Not a problem, but more a small suggestion: A way to limit the amount of modifier and upgrade slots on a tool to just the amount it comes made with, with no way to add extra upgrade slots past the original amount. Should help to make the mod more balanced in lighter packs, but still having plenty of options with materials and such. 

### Other mods

n/a

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KonSola5** [comment]
You can disable bonus modifiers by creating empty `.json`s named like the modifier.

The originals should be located in `data/tconstruct/tinkering/modifiers` in the Hephaestus .jar.
