### ISSUE TITLE
Items and fluids not rendering in casting tables or basins or smelter, REI won't auto-move recipes or move GUI out of the way in Tinker's Station/Anvil—Quilt mod loader seems to be the cause

### ISSUE THREAD

**Issue by viedemarli** [Alpha-s-Stuff/TinkersConstruct#85]
### Minecraft Version

1.20.1

### Fabric Version

0.14.24

### Fabric API Version

0.90.4

### Hephaestus Version

3.6.3.232

### Describe your issue

With the Quilt mod loader active—not Fabric, as Fabric seems to work just fine—any items put into a casting table or basin do not render; neither do fluids being poured or when they are in the smelter itself. Everything still works—I can still pour liquid and advance into Hephaestus/TC. I've built a smelter and it works just fine, no crashes or even errors.

Following the advice given at the top, I've switched back to Fabric for the time being since none of my mods seem to suffer for it. I don't know why Quilt is causing the issue, but I figured I'd note it since I did not see any closed or open issues with this specific one. I have seen others, but those involve Sodium, and mine did not. 

Also of note:
- Roughly Enough Items won't auto-move Hephaestus/TC recipes into both the vanilla crafting table or Crafting Station. It says something like "It cannot move at this time" and something about an incompatibility.
- REI also overlaps the right-side GUI when looking at a tool's modifiers and parts in the Anvil and Tinker's Station; it does not auto-move around it like REI usually does with other GUI mods, but that is as easy as using CTRL+O to hide the GUI. 

Both of the above only happen on Quilt as well. If you'd rather I make two separate issues about it I definitely can but they're so minor that I thought I'd just tack them on here.

### Other mods

Apart from Sodium I'm using the whole suite of Sodium, Sodium Extras, Indium, Iris Shaders (with a shader enabled—MakeUp Ultra Fast to be specific) and LazyDFU. They all work with Hephaestus/TC swimmingly!

I have many other mods too, but none of them interact and cause this specific issue except Quilt itself, and perhaps Quilted Fabric API. However, some of the mods do cause _very_ minor issues unrelated to the one I'm making a ticket on:

- Continuity causes all-white fluids for all fluids (except water and lava). Removing it fixes it
- Diggus Maximus also doesn't fully work—using the grave key only minds a 3x3 area instead of what it usually does (mine an area for as much durability as a tool has), but that could be a feature of Hephaestus/TC that I didn't know about.
- Not sure what mod is causing it, if any, since it happened with only Hephaestus/TC, but I can't open chests in the 1.20.1 version. 1.18.2 I could just fine; don't know what caused that but I did see someone else having the same issue.

If any of these warrant a separate ticket please let me know and I'll make them. I just figured because none of them really "break" anything (I have workarounds for all of these issues including the last one, which is. just using regular chests to store things) they aren't worth it since nothing is causing crashes.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium, Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by AlphaMode** [comment]
Have you made a issue report on quilted fabric api? I've had similar issues with it before.
Can you also provide your log file? I'd be able to see if there any internal errors in the log.

**Comment by viedemarli** [comment]
Don't have to—I'm stupid and it was Continuity causing the issue. Disabled QFAPI and the mods it used, re-enabled one-by-one, no issue. Saw Continuity was disabled and thought, 'well it's causing the white-fluid, so maybe it's causing the rendering issue too', re-enabled it on a whim, and popped into the world: white copper fluid when I smelted it down, and items in the basin and casting table are invisible. I feel so dumb now, I'm so sorry.

As for the log file, I apologize since it only said crash log, and since the game didn't crash... [Here it is](https://pastebin.com/AnfAgyRW), I think—I do use MultiMC but that's never been an issue. This version is with Continuity enabled. A couple of the mods (Croptopia, Tiered, and WWOO) I do not use but keep them so I can update my mod list as new Minecraft versions release. You can ignore them since I know they still show up in the mod list at the top.

**Comment by AlphaMode** [comment]
This should be fixed in latest
