### ISSUE TITLE
I wanna make an addon

### ISSUE THREAD

**Issue by LaithAlshakhs** [Alpha-s-Stuff/TinkersConstruct#86]
### Minecraft Version

1.20.1

### Fabric Version

0.14.22

### Fabric API Version

0.89.0+1.20.1

### Hephaestus Version

1.20.1-3.6.3.232

### Describe your issue

I wanna make an addon, but I couldn't find maven

### Other mods

Nothing

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by AlphaMode** [comment]
It's https://mvn.devos.one/snapshots/ I can make a template if needed

**Comment by LaithAlshakhs** [comment]
is this the right format modImplementation "slimeknights.tconstruct:TConstruct:1.20.1:3.6.3.232" ?

**Comment by KonSola5** [comment]
From my own addon:
```
modImplementation "slimeknights.tconstruct:Hephaestus:1.20.1-3.6.3.232"
modImplementation("slimeknights.mantle:Mantle:${minecraft_version}-${mantle_version}")
```

where `minecraft_version=1.20.1` and `mantle_version=1.9.254`

Hephaestus is bundled with Mantle, but for some reason not including Mantle manually can cause the compiler/IDE to not find some classes.

**Comment by LaithAlshakhs** [comment]
I’ve added it thanks
