### ISSUE TITLE
Crash after using on blocks without use on block event with tconstruct tools

### ISSUE THREAD

**Issue by JieningYu** [Alpha-s-Stuff/TinkersConstruct#9]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

0.14.8

### Fabric/Quilt API Version

0.58.0+1.18.2

### Tinkers' Construct Version

3.5.1-DEV.515379a

### Describe your issue

ex. right click andesite with a Tinker's axe and crash.
but it won't crash when the block has action when be used (ex. stripping logs)

### Crash Report

https://paste.mozilla.org/7E2KN6DR/raw

### Other mods

  [??] agape_space_18_2-0.5.15
  [??] appliedenergistics2-11.1.5
  [??] architects-palette-fabric-2.2
  [??] architectury-4.7.78-fabric
  [??] badpackets-fabric-0.1.2
  [??] bitsandchisels-2.6.13
  [??] cloth-config-fabric-6.2.62
  [??] cobblegen-v1.10b33+mc1.18.x
  [??] Controlling-fabric-1.18.2-9.0+21
  [??] create-1.18.2-0.5.0c-708
  [??] createplus-1.0.0
  [??] CustomSkinLoader_Fabric-14.14-SNAPSHOT-343
  [??] customsplashscreen-1.2.0
  [??] dawn-3.3.2
  [??] debugify-1.11.0-fabric-1.18.2
  [??] entityculling-fabric-mc1.18-1.5.1
  [??] ExtendedDrawers-1.3.2+mc.1.18.2
  [??] fabric-api-0.58.0+1.18.2
  [??] fabric-language-kotlin-1.8.2+kotlin.1.7.10
  [??] farmers-delight-fabric-1.18.2-0.2.1
  [??] ftb-chunks-fabric-1802.3.6-build.147
  [??] ftb-library-fabric-1802.3.6-build.140
  [??] ftb-quests-fabric-1802.3.8-build.101
  [??] ftb-teams-fabric-1802.2.6-build.51
  [??] ftbbackups2-forge-1.18.2-1.0.13
  [??] here-be-no-dragons-1.0.0
  [??] indium-1.0.7+mc1.18.2
  [??] indrev-1.14.0-BETA
  [??] InventoryProfilesNext-fabric-1.18.2-1.6.0
  [??] iris-mc1.18.2-1.2.6
  [??] item-filters-fabric-1802.2.7-build.33
  [??] kibe-1.9.9-BETA+1.18
  [??] kubejs-create-fabric-1802.2.2-build.26
  [??] kubejs-fabric-1802.5.4-build.533
  [??] lazydfu-0.1.2
  [??] lithium-fabric-mc1.18.2-0.7.10
  [??] logical_zoom-0.0.14
  [??] mcwifipnp-1.5.6-1.18.2-fabric
  [??] modmenu-3.2.3
  [??] mostructures-1.4.2+1.18.2
  [??] notenoughcrashes-4.1.6+1.18.2-fabric
  [??] nounusedchunks-1.1
  [??] owo-lib-0.7.2+1.18
  [??] polylib-fabric-1801.0.2-build.13
  [??] promenade-2.6.3
  [??] questsadditions-fabric-1.18.2-1.3.1
  [??] reeses_sodium_options-1.4.4+mc1.18.2-build.46
  [??] replaymod-1.18.2-2.6.6
  [??] rhino-fabric-1802.1.14-build.206
  [??] roughly-enough-characters-0.0.6+1.18.2-fabric0.13.3
  [??] RoughlyEnoughItems-8.3.519
  [??] sodium-extra-0.4.6+mc1.18.2-build.46
  [??] sodium-fabric-mc1.18.2-0.4.1-replay
  [??] starlight-1.0.2+fabric.89b8d9f
  [??] TConstruct-1.18.2-3.5.1.DEV.515379a
  [??] worldedit-mod-7.2.10
  [??] WorldEditCUI-1.18.2+01
  [??] wraith-alloy-forgery-2.0.13+1.18
  [??] wthit-fabric-4.11.0
  [??] YungsApi-1.18.2-Fabric-2.0.8
  [??] YungsBetterDesertTemples-1.18.2-Fabric-1.3
  [??] YungsBetterDungeons-1.18.2-Fabric-2.1.0
  [??] YungsBetterMineshafts-1.18.2-Fabric-2.2
  [??] YungsExtras-1.18.2-Fabric-2.1.0

### Tried reproducing with just Tinkers?

I will go do that now

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues

**Comment by AlphaMode** [comment]
Fixed in latest commit
