### ISSUE TITLE
Fuel tanks input is broken on the latest version

### ISSUE THREAD

**Issue by sfwtn** [Alpha-s-Stuff/TinkersConstruct#90]
### Minecraft Version

1.20.1

### Fabric Version

0.14.24

### Fabric API Version

0.90.7+1.20.1

### Hephaestus Version

1.20.1-3.6.3.241

### Describe your issue

Starting with version 1.20.1-3.6.3.241 it is impossible to input any liquid via buckets into fuel tanks. When clicking with a full bucket on a fuel tank it will remove bucket's content and display an input message, however no liquid will actually be deposited. Output still seems to work.
This issue is not present on past versions:
- 1.20.1-3.6.3.240
- 1.20.1-3.6.3.232

Steps to reproduce:
1. Place a fuel tank in the world
2. Try to interact with it using any bucket with liquid

### Other mods

This issue is reproducible without any other mods and is specific to the Fabric port.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by Vinesauced** [comment]
Can confirm that this issue happens in 3.6.3.241 and not at all in 3.6.3.240

**Comment by Lv44EnderShaman** [comment]
Can also confirm this issue. Just happened to me in 3.6.3.241 as well.

**Comment by AlphaMode** [comment]
I recommend just going to the previous version on cf.

**Comment by AlphaMode** [comment]
Currently I'm rewriting transfer so it might be a little bit before the next release

**Comment by Lv44EnderShaman** [comment]
Thanks for the advice. Definitely taking it under advisement; We appreciate the hard work you're putting into this and look forward to when the next release resolves this issue.

**Comment by AlphaMode** [comment]
Fixed in 3.6.4.261
