### ISSUE TITLE
Crash with hopper

### ISSUE THREAD

**Issue by yu-re-ka** [Alpha-s-Stuff/TinkersConstruct#92]
### Minecraft Version

1.20.1

### Fabric Version

0.14.24

### Fabric API Version

0.90.7+1.20.1

### Hephaestus Version

1.20.1-3.6.3.232

### Describe your issue

Placing hoppers on a meltery results in buggy behavior, sometimes the server crashes

### Crash Report

https://paste.debian.net/1299002/

### Other mods

See logs, no other mods appear in the stack trace

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium, Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by 1Bulgarian** [comment]
This is a bug that is happening in every version after 222, items that enter through a chute crash the server, each time that the server is loaded. You can do that not only with hoppers, droppers also cause the same bug.

**Comment by AlphaMode** [comment]
Paste bin is broken, but this should be fixed in latest
