### ISSUE TITLE
A Strange Number

### ISSUE THREAD

**Issue by link-fgfgui** [Alpha-s-Stuff/TinkersConstruct#93]
### Minecraft Version

1.20.1

### Fabric Version

0.15.1

### Fabric API Version

0.91.0-1.20.1

### Hephaestus Version

3.6.3.240

### Describe your issue

why a strange number? 5333 1/3 mB?
![image](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/96362154/66dc3b92-3a95-47db-be88-40a4c22010b9)

### Other mods

Jade
Jade Addons
modmenu

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by link-fgfgui** [comment]
It should be 4320mB

**Comment by KonSola5** [comment]
According to the source code and the toolip:
![gauge](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/125081901/7c3695c3-4168-46e0-bff8-7e4eae2a791a)

https://github.com/Alpha-s-Stuff/TinkersConstruct/blob/8d64ca2073c528d4183dd6add172756c99bcb018/src/main/java/slimeknights/tconstruct/smeltery/block/component/SearedTankBlock.java#L108
... the gauge stores 48 ingots. (which is consistent with Tinkers' Construct).
In Hephaestus, an ingot is 111 ¹/₉ mB (9000 droplets) as opposed to ~~144 mB~~ 90 mB like it is in Tinkers' Construct.
48 * 111 ¹/₉ mB = 5333 ¹/₃ mB.

**Comment by link-fgfgui** [comment]
so,maybe it is not a bug.
