### ISSUE TITLE
Smeltery completely broken for 1.20.1 (Duplication Glitch, Ghost Items & Fuel Tank not working)

### ISSUE THREAD

**Issue by EvieTheOwl** [Alpha-s-Stuff/TinkersConstruct#95]
### Minecraft Version

1.20.1

### Fabric Version

0.15.1

### Fabric API Version

0.91.0

### Hephaestus Version

1.20.1-3.6.3.241

### Describe your issue

The issues are best explained through video: https://drive.google.com/drive/folders/1dR69la1FFqnWUe6FEAQoBn84jMHOBoUU?usp=drive_link

- You get a response saying fuel is accepted. In this case I used lava. In reality it doesn't render and the smeltery does not increase it's fuel amount.
- Nasty duplication glitch when inserting anything into the smeltery controller via a hopper.
- Ghost items within the Smeltery Controller that jump about. I honestly have no idea what's going on here.

### Other mods

No others. Tested alone to make sure it wasn't one of the mods I added to my modpack.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by EvieTheOwl** [comment]
#90 Apologies the fuel tank input has a duplicate issue

**Comment by CoderXL1** [comment]
The lava tank in 3.6.3.240 is working well.

**Comment by AlphaMode** [comment]
Latest version should fix this
