### ISSUE TITLE
JEI or EMI Compat

### ISSUE THREAD

**Issue by link-fgfgui** [Alpha-s-Stuff/TinkersConstruct#96]
### Minecraft Version

1.20.1

### Fabric Version

0.91.0-1.20.1

### Hephaestus Version

3.6.3.240

### Problem description

Alloy formulations cannot be displayed on EMI.

### Suggested solution

If possible, could you please add JEI or EMI compatibility? I think EMI is a great mod.

### Alternatives considered

[extra-mod-integrations](https://modrinth.com/mod/extra-mod-integrations) is in progress.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by AlphaMode** [comment]
I don't plan on supporting EMI, addons can do it if they want to. And JEI is a pain to get working on fabric
